# Generated by Django 4.0.4 on 2022-05-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='familiar',
        ),
    ]
