# Generated by Django 4.0.4 on 2022-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_remove_familiar_adult_remove_familiar_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='DOB'),
        ),
    ]
